server:
  port: ${studentPort:8282}
deployed:
  from: ${destination:WindowLocalMachine}
---
spring:
  spring:
    config:
      activate:
        on-profile: H2Mem
  #profiles: H2Mem
  h2:
    console.enabled: true # to access DB via URL -->http://localhost:8080/h2-console
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    #hibernate.ddl-auto: none
    show-sql: true
  datasource:
    url: jdbc:h2:mem:studentdb # use jdbc:h2:file:/data/studentdb for file based H2 DB
    driverClassName: org.h2.Driver
    username: ${SPRING_DATASOURCE_USERNAME:sa}
    password: ${SPRING_DATASOURCE_PASSWORD:}
    initialization-mode: always # THis runs data.sql
    continue-on-error: true
db:
  source: inMemH2
---
spring:
  config:
    activate:
      on-profile: H2File
  #profiles: H2File
  h2:
    console.enabled: true # to access DB via URL -->http://localhost:8080/h2-console
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    #hibernate.ddl-auto: update # to add only updated columns or schema changes,indirectly persisting the data and not dropping the table on startup (default value is "create-drop")
    show-sql: true
  datasource:
    url: jdbc:h2:file:~/studentdb #  for file based H2 DB stred in C:/Users/anupm/studentdb.mv.db
    driverClassName: org.h2.Driver
    username: ${SPRING_DATASOURCE_USERNAME:sa}
    password: ${SPRING_DATASOURCE_PASSWORD:}
    initialization-mode: always # this runs data.sql file
    continue-on-error: true
db:
  source: inMemFileH2

---
spring:
  config:
    activate:
      on-profile: AzureDB
  #profiles: AzureDB
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
    hibernate.ddl-auto: none # by default created the tables/ schemas
    show-sql: true
    defer-datasource-initialization: true
    init.mode: always # this runs data.sql file but only for embedded/in memory DB
  datasource:
    url: jdbc:mysql://studentmysqldb.mysql.database.azure.com:3306/studentdb?serverTimezone=UTC
    username: mydemouser
    password: admin$123
    initialization-mode: always # this runs data.sql file but only for embedded/in memory DB
    continue-on-error: true
db:
  source: AzureDB1
logging:
  level.org.hibernate.SQL: DEBUG

---